language: node_js
node_js: stable
sudo: required

# 构建的分支
branches:
  only: 
    - master

before_install:
  # 参考：https://yarnpkg.com/lang/en/docs/install-ci/
  # Repo for Yarn
  - sudo apt-key adv --fetch-keys http://dl.yarnpkg.com/debian/pubkey.gpg
  - echo "deb http://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
  - sudo apt-get update -qq
  - sudo apt-get install -y -qq yarn


# S: Build Lifecycle
install: 
  - yarn install

script:
  - yarn run build

# 参考：https://docs.travis-ci.com/user/deployment/pages/
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN # github 上的token环境变量
  local-dir: ./dist/ ## 根据情况自定义到静态文件输出目录
  target-branch: gh-pages
  verbose: true
  on:
    branch: master

cache:
  yarn: true